### ISSUE TITLE
Street detection splits wrong

### ISSUE THREAD

**Issue by mahype** [awsmug/shipcloud-for-woocommerce#101]
In the plugin we have an option called "Street detection". This option splits the street from the street number automatically. In the case by a user we had the following results which hopefully are reproducable:

- "Zum Weiher 12" > "Zum Weihe r"
- "Heidenfeldstraße 15" > "Heidenfeldstraß e"

The problem is that the number is lost and the last char of the street will be taken instead.

**Comment by andrecedik** [comment]
Ok, it seems to be not as easy as I thought. 

When you enter the address `Straße des 17. Juni 152` in the street address field:

![checkout_housenumber_in_address_field](https://user-images.githubusercontent.com/5707341/27790049-2324995a-5fef-11e7-8adc-b3fd925487f3.png)

... then the splitting still has a problem:
![order_housenumber_in_address_field](https://user-images.githubusercontent.com/5707341/27790079-53e9f5e4-5fef-11e7-8bb2-3629cc518980.png)

When the customer enters the house number in the 2nd field (*Apartment, suite, unit etc.*) it will be used as for the c/o entry.

**Comment by ScreamingDev** [comment]
btw: Was part of the bugfix too. Tested with this set:

```
return [
			['This, That, and the other Street 123', 'This, That, and the other Street', '123'],
			['Sesamstraße', 'Sesamstraße', null],
			['   Einbahnstraße  ', 'Einbahnstraße', null],
			['   Ei nb ahns traß e  ', 'Ei nb ahns traß e', null],
			['Züm Humpfen Stobel 12a', 'Züm Humpfen Stobel', '12a'],
			['Heidenackerweg 15', 'Heidenackerweg', '15'],
			['Straße des 17. Juni 152', 'Straße des 17. Juni', '152'],
		];
```

**Comment by andrecedik** [comment]
Cool. 👍  Do you have a commit that we can link here @ScreamingDev?

**Comment by ScreamingDev** [comment]
Oh, yes. This one @andrecedik 
https://github.com/awsmug/shipcloud-for-woocommerce/commit/f833d9790cb2e08692d43f2a14bf69b94840ae7c
