### ISSUE TITLE
Change wc_shipcloud_shipping to shipcloud

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#118]
The navigation entry for editing the shipcloud settings within the shipping tab has changed. It's now named `shipcloud` which is why redirecting to the url `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=wc_shipcloud_shipping` results in the entry not being "active" (written in bold letters).

**Comment by ScreamingDev** [comment]
Also keep this slug alive by redirecting (304) to the new one.

**Comment by andrecedik** [comment]
Not an issue any more.
