### ISSUE TITLE
Bug: __construct can not return value

### ISSUE THREAD

**Issue by ScreamingDev** [awsmug/shipcloud-for-woocommerce#120]
See `\Woocommerce_Shipcloud_API::__construct` (`includes/shipcloud/shipcloud.php:78`):

```
if ( empty( $this->settings[ 'api_key' ] ) )
			{
				return new WP_Error( 'shipcloud_api_error_no_api_key', __( 'No api key given', 'shipcloud-for-woocommerce' ) );
			}
```

This part has to be solved/removed.

- Please look up why it is used
- Solve it via Exceptions or different.

**Comment by ScreamingDev** [comment]
Also on top of release/1.4 @andrecedik  . Please check some things in the backend that they didn't break.

**Comment by andrecedik** [comment]
LGTM 👍
