### ISSUE TITLE
Display correct parcel template name when editing order

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#123]
I've saved a parcel template which now displays as `DHL Express (1 Day)(Parcel)` on the parcel templates overview page. When editing an order I get the old title from the parcel template, which was `DHL - Express (1day)`.

<img width="934" alt="parcel_template_in_order" src="https://user-images.githubusercontent.com/5707341/28837798-59b6bea6-76ee-11e7-884b-aeb1bb8e52fc.png">

**Comment by ScreamingDev** [comment]
Pushed in release/1.4 branch . Please double check @andrecedik .

**Comment by andrecedik** [comment]
LGTM 👍
