### ISSUE TITLE
open_basedir prevents proper handling of curl requests

### ISSUE THREAD

**Issue by ScreamingDev** [awsmug/shipcloud-for-woocommerce#128]
Follow relocation of cURL will be prevented when open_basedir is set to true in PHP config.
As of PHP 5.3 and above we are able to get around this by:

- Set open_basedir to false during the request (via `ini_set`).
- Use http://php.net/manual/de/function.curl-setopt.php#95027
- Use http://php.net/manual/de/function.curl-setopt.php#113682

**Comment by ScreamingDev** [comment]
Keeping this open to track the response. If there is none in 1.4.2 then it can be closed.

**Comment by andrecedik** [comment]
Should be solved. I haven't heard from the user again. Closing this now.
