### ISSUE TITLE
Shipping labels don't get created in 1.4.0

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#130]
When creating a shipping label the parameter `create_shipping_label` isn't transmitted anymore. Therefore all shipments are "prepared shipments" and not "real shipments" carrying a shipping label / tracking number.

**Comment by ScreamingDev** [comment]
This is on top of the `release/1.4` branch now. I already checked this and got a label PDF + the field is forwarded.

![image](https://user-images.githubusercontent.com/2559177/28933467-71c0fb8e-787d-11e7-89d7-3d88ca2ea6df.png)

Feel free to double check @andrecedik

**Comment by andrecedik** [comment]
I was able to create shipping labels from single orders as well as using batch create 👍
