### ISSUE TITLE
Change of shipping methods should update default carrier

### ISSUE THREAD

**Issue by ScreamingDev** [awsmug/shipcloud-for-woocommerce#138]
![image](https://user-images.githubusercontent.com/2559177/29240507-3bda6bcc-7f67-11e7-8188-b6585753483f.png)

**Comment by andrecedik** [comment]
Hmm, if someone changes the carriers being used, should the default shipping method maybe removed? This way, the admin **has to** select a new one, instead of us picking a new one, the user might not want as a default.

**Comment by andrecedik** [comment]
Ok, just figured out, that we're already selecting the next active carrier, once the default carrier is deactivated. When no carrier is selected, the dropdown for selecting the default carrier is hidden. Closing this issue now
