### ISSUE TITLE
Data for shipping classes has weird automatic deletion bug

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#139]
We've got a customer who, after updating the plugin, couldn't save the dimensions (width, length, height) as well as the weight for a given shipping class, because when entering dimensions, the weight was being deleted and vice versa. 

Conditions:
- WordPress 4.8.1
- WooCommerce 3.1.1
- plugin (old version 1.2.0 / new version 1.4.1)

**Comment by ScreamingDev** [comment]
Dunno. I was able to change it @andrecedik 
Was 1,2,3,4 and now ...
![image](https://user-images.githubusercontent.com/2559177/33342040-fc04f142-d480-11e7-8dc8-0a1414c49e5e.png)

**Comment by andrecedik** [comment]
Weird. I'm going to close this for now. Maybe it was a side effect of another plugin or something. Will reopen it, if there's another customer with this bug. Since we're currently releasing 1.6 I'm pretty sure this isn't a problem anymore.
