### ISSUE TITLE
Plugin Meta: Show min PHP Version

### ISSUE THREAD

**Issue by ScreamingDev** [awsmug/shipcloud-for-woocommerce#145]
See https://make.wordpress.org/plugins/2017/08/29/minimum-php-version-requirement/

**Comment by ScreamingDev** [comment]
@mahype do we require PHP 5.5 ? 5.4 ?
Or shall I add a code sniffer for that to find out? (and keep track of it / test it / CI)

**Comment by andrecedik** [comment]
Fixed with https://github.com/awsmug/shipcloud-for-woocommerce/commit/e8f949635ccd28418226dd4f9a99b7c9b2686cb1
