### ISSUE TITLE
Bugs in address splitting algorithm

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#158]
Streetname and number are being splitted wrongfully when one of the following is the case:

- There are one or more slashes between the number parts (e.g. "Mittelweg 158a/162" --> 158a)
- There is a dash between two numbers (e.g. "Mittelweg 158a-162" --> 158a)

**Comment by ScreamingDev** [comment]
Hm. How about just splitting on the first occasion of a number and Bob's your uncle.
No fancy regex, nothing. Just dumb splitting at numbers. Would solve almost everything (I hope).

@andrecedik 
So simple that we can have it in 1.6 already.

**Comment by andrecedik** [comment]
Fixed via #168
