### ISSUE TITLE
Make prepared shipments editable

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#26]
After saving a shipment, the shop admin only has the chance to create a shipping label from the backoffice. She/He is not able to adjust the data before that. So when the admin realizes that there's an error in the data provided she/he can only delete the shipment and create a new one.

**Comment by andrecedik** [comment]
Removing the milestone for now so we can get out release 1.5.0

**Comment by ScreamingDev** [comment]
As discussed today this has been solved in the new interface and is therefor closed.
FYI @andrecedik
