### ISSUE TITLE
Introduce package type

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#66]
We've introduced a `type` attribute to the `package` object. Using this makes it possible e.g. to allow customers the use of the carrier Deutsche Post for sending smaller items like t-shirts or cellphone cases. It is also needed for sending bulk items via one of the carriers that support this feature.

There are currently 5 different types of package type that can be used:
* books ([example](https://developers.shipcloud.io/recipes/#deutsche-post-bchersendung))
* bulk ([example](https://developers.shipcloud.io/recipes/#dhl-bulk-shipments))
* letter ([example](https://developers.shipcloud.io/recipes/#deutsche-post-brief))
* parcel ("normal" shipping label)
* parcel_letter ([example DHL](https://developers.shipcloud.io/recipes/#deutsche-post-warensendung) | [example DPD](https://developers.shipcloud.io/recipes/#dpd-parcel-letter))

**Comment by ScreamingDev** [comment]
Do I remember correct @andrecedik ?

We add a dropdown containg this in ...

- ... the bulk action
  - default will be "normal"
  - parcel_letter will be added dynamicly as soon as DHL/DPD is chosen
- ... the order edit view
  - same as bulk action but for this single order
- ... the parcel templates / and edit screen
  - existing parcel templates will be migrated by setting the default "parcel" 
  - the create or edit screen gets the same dropdown as in the bulk action.

What shall be the labels / the names for the user?
I see the internal names in you list but not how the user shall call them.

**Comment by andrecedik** [comment]
The default should always be `parcel` (even for DPD). Currently the only exception is Deutsche Post. You should use `letter` as default package type when using `DPAG` as a carrier. 

For the English Version you can use the terms that our api returns ("books", "bulk", "letter", "parcel", "parcel letter"). For the German version we should use the following "translations":
* books = *Büchersendung*
* bulk = *Übergröße*
* letter = *Brief*
* parcel = *Paket*
* parcel letter = *Warenbrief* 
  * DPD actually calls the product [*PARCELLetter*](https://www.dpd.com/de/versandmoeglichkeiten/unser_versandangebot/parcelletter)
  * so maybe we should call it the same when DPD or iloxx is the carrier?!?

**Comment by andrecedik** [comment]
Ok, I've talked to @ScreamingDev and realized that this needs a bit more information to make things clear(er). 

To create a shipping label shipcloud needs these 3 values that one gets when querying the [carriers endpoint](https://developers.shipcloud.io/reference/#carriers) of the api:
- `carrier` - key that identifies a carrier (eg. `dhl`)
- `service` - key that identifies the service that should be used (a normal shipment is defined by the value `standard`, there's also express shipping `one_day` and `one_day_early`, as well as `returns` and `same_day`
- `package.type` - key that identifies the type of the box that will be used for shipping (see descriptions above)

### Settings
Currently admins can select from the WooCommerce settings, which carrier and service they would like to use:
![woocommerce_settings_shipcloud](https://user-images.githubusercontent.com/5707341/27868587-84e596f8-619d-11e7-8bb8-4973549ff0fc.png)

To make the display clearer, the admin should just see the carrier names and therefore have to activate the ones they would like to use. 

### Create shipping label from order detail page
![edit_order_shipping_method](https://user-images.githubusercontent.com/5707341/27869060-fdea996c-619e-11e7-9f3d-887606f55b33.png)

When it comes to creating a shipping label, the admin should be provided with a triplet of dropdowns - one for carriers, one for services and one for the package type. The value selected from the carriers dropdown should update the services dropdown to show only the services that are available for the selected carrier. If a service was preselected and the new carrier does not support this service, `standard` should be the default one selected.

The selected carrier should also update the package type dropdown so only the package types supported by this carrier are shown. The fallback for package types should be `parcel`.

### Parcel templates
When creating new parcel templates, the single dropdown should be replaced (just like in the create shipping label form) with 3 dropdowns showing the three selections for carrier, service and package type.

![add_new_parcel_template](https://user-images.githubusercontent.com/5707341/27869233-96680da0-619f-11e7-90d2-0133acc086b3.png)

**Comment by ScreamingDev** [comment]
So. Please test this @andrecedik .

I left over one thing on purpose: Only the selected carriers can be used for template etc.
This is a problem as unselecting carriers may break return labels or templates.
We may discuss this further and shift it to another release.

There were some other problems I have to tell next meeting.

**Comment by andrecedik** [comment]
Looks great so far. Although there are some things we can adjust for an easier user experience I think this is good enough to get people started.

I just have one question. When viewing the defined parcel templates because of the way we've structured the request before, the name implies that the service has been preselected:
![woocommerce_parcel_template_overview](https://user-images.githubusercontent.com/5707341/28510772-724714b6-704a-11e7-871e-e1aea82c301d.png)

But when you edit the parcel template, this hasn't been selected:
![woocommerce_parcel_template_edit](https://user-images.githubusercontent.com/5707341/28510812-9830f80e-704a-11e7-9f3d-bd099d29efcb.png)
My best guess would be that preselecting the service isn't possible due to the way this has been saved in the past, right? Maybe we should add a note to the release notes, that one has to adjust their parcel templates.

**Comment by andrecedik** [comment]
Oh no - I just found a bug @ScreamingDev 😱 
When you save a parcel template the data doesn't gets saved in the database (correctly). 

I selected DHL + Standard + Parcel and saved the parcel template. After the page reloaded, nothing was selected in the dropdowns. When you return to the parcel templates overview page, you get this:

![woocommerce_parcel_template_overview_after_saving](https://user-images.githubusercontent.com/5707341/28510954-29797002-704b-11e7-8775-c33bc33c1e8d.png)

So the name gets overwritten (by an empty string), but the entries for service and package type won't get saved.

**Comment by andrecedik** [comment]
😂  it seems to "only" be a display bug on the parcel template pages. When using the parcel template to fill the input fields in an order, everything is fine:

![woocommerce_using_parcel_template_in_order_after_saving](https://user-images.githubusercontent.com/5707341/28511058-b57dbac2-704b-11e7-90c2-fea97255903f.png)

**Comment by andrecedik** [comment]
Argh, there seems to be another bug when creating orders. I have the following order data:
![woocommerce_order_shipping_center](https://user-images.githubusercontent.com/5707341/28511381-3ad93bc8-704d-11e7-9735-ac319a50212f.png)

But when I submit the order, the api receives the following data:
```json
{
  "order_id": "31",
  "to": {
    "country": "DE"
  },
  "package": {
    "width": "20",
    "height": "20",
    "length": "20",
    "weight": "2",
    "description": "package description",
    "type": "parcel"
  },
  "carrier": "dhl",
  "service": "standard",
  "other_description": "",
  "isReturn": "false",
  "action": "shipcloud_create_shipment_label",
  "create_shipping_label": true,
  "reference_number": "Order 31",
  "notification_mail": "andre@shipcloud.io"
}
```

Everything I've added through the parcel template matches, but there's no recipient data being submitted. Also the entries `isReturn` and `action` shouldn't be submitted to the api.

**Comment by andrecedik** [comment]
When trying to bulk create shipping labels, there's no dropdown to use a parcel template anymore. 😢

**Comment by andrecedik** [comment]
Ok, here's a little status recap:
✅ The split between carrier, service and package type works 👍 
✅ Parceltemplates can be definded using the new notation (carrier, service, package type)
✅ Parceltemplates can be selected from within an order and are filling the form correctly
❕ The parceltemplate titles aren't shown correctly on the parcel template overview page (should be fixed via https://github.com/awsmug/shipcloud-for-woocommerce/pull/117)
❕ The list of carriers still has the aggregate of carrier + service. Just use the carriername to be selected by the admin. The user can define parcel templates to select the desired combination.

**Comment by ScreamingDev** [comment]
@andrecedik regarding:

> The list of carriers still has the aggregate of carrier + service. Just use the carriername to be selected by the admin. The user can define parcel templates to select the desired combination.

Somewhere I mentioned that this is a left over on purpose. I suggest deploying 1.4 without that as 1.4 was about package types. In addition it takes some time to clean this part up.

Shall we do it anyway and release on Thursday or do we push 1.4 asap?

(be prepared @mahype , might be the last thing in this issue)

**Comment by andrecedik** [comment]
Ok, let's leave it this way to get v1.4.0 out. 😉 

I've tested the parcel templates overview page. It's kind of weird, that you have to save the parcel templates again, to get the new title but as long as it works, I'm down.
<img width="391" alt="parcel_templates_overview" src="https://user-images.githubusercontent.com/5707341/28837696-064fb4fc-76ee-11e7-8162-ea864274d9a3.png">

**Comment by andrecedik** [comment]
This is weird. Shouldn't it be displayed the same way when trying to select a parcel template from within an order?

<img width="934" alt="parcel_template_in_order" src="https://user-images.githubusercontent.com/5707341/28837798-59b6bea6-76ee-11e7-884b-aeb1bb8e52fc.png">

Here it says `DHL - Express (1day)` instead of `DHL Express (1 Day)(Parcel)`

**Comment by ScreamingDev** [comment]
Hey @andrecedik ,

I'm totally with you

> It's kind of weird, that you have to save the parcel templates again, to get the new title but as long as it works, I'm down.

This is part of #116 and similar. In general you should only have to save the new (broken) ones again. The old should be still good.

And yes:

> This is weird. Shouldn't it be displayed the same way when trying to select a parcel template from within an order?

This is weird as the display logic for both parts is still spread across multiple redundant functions. Still some duplicate code in there. I managed to make the surrounding view centralised (more to say: the left part of it, as this has changed) but not yet the right part.

**Comment by andrecedik** [comment]
Ok, I've created a new issue for displaying the carrier names in the settings (https://github.com/awsmug/shipcloud-for-woocommerce/issues/124). So this is out of the scope of this ticket.

**Comment by andrecedik** [comment]
Ok, I'm closing this issue now and then we can release version 1.4.0 🎉  🍰  🍾
