### ISSUE TITLE
Add input field for phone to from and to address

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#81]
Especially when using express services like DHL express, UPS express, FedEx, etc. the carriers require a phone number to be provided when creating a shipping label. This is due to the fact that they want to make sure that the time between pickup and delivery is as short as possible.

For this to work we would only need an additional input field in the "Absenderadresse" as well as in the "Empfängeradresse".

**Comment by andrecedik** [comment]
Ok, this becomes even more important because DHL (when using "DHL Ship") also needs the phone number of the recipient when sending shipments out of Germany.

**Comment by sourcerer-mike** [comment]
Solution:

- New field for sender and recipient
- New field is mandatory/required

Hints:

- Mandatory fields block customers from buying crap. How about we make it optional and put the shop owner number there in case someone does not want to pollute the world with his data?
- We can't really determine what's outside the country or inside. Except this is down to Germany / Non-Germany, then it should be simple to distinguish mandatory and optional.

**Comment by andrecedik** [comment]
I found out that the phone number isn't mandatory. But we should make it possible to enter this by adding an additional input field.

**Comment by ScreamingDev** [comment]
WooCommerce had such field already.

![image](https://user-images.githubusercontent.com/2559177/27510317-2b58370e-590e-11e7-9153-6e944eac19a5.png)

I mapped it and added an additional field to the backend:

![image](https://user-images.githubusercontent.com/2559177/27510329-4c3e3d24-590e-11e7-8207-c427e061282e.png)

Please have a look if this solves it.

**Comment by andrecedik** [comment]
Looks good. I checked it and received `"phone":"+491234567890"` via our api.

One thing though, @ScreamingDev. Is it possible to also add an input for phone number to the senders address data for it to be send as part of the to-address?

**Comment by ScreamingDev** [comment]
Hm. This is in the repo without any ping here @andrecedik . So please test this issue with this branch:
https://github.com/awsmug/shipcloud-for-woocommerce/tree/release/1.4

**Comment by andrecedik** [comment]
Unfortunately I'm still seeing the phone number only for the recipient address and not the sender address. Any ideas @ScreamingDev ?

![woocommerce_phone](https://user-images.githubusercontent.com/5707341/28266483-68adad84-6af5-11e7-94de-2789b4003cb1.png)

**Comment by andrecedik** [comment]
@ScreamingDev how can we move this further? Can you tell me where a user can set this within WooCommerce? Your previous screenshot showed the billing address. But I am talking about the sender address which will be prefilled by the data the user has configured in the shipcloud plugin settings (`/wp-admin/admin.php?page=wc-settings&tab=shipping&section=shipcloud`).

<img width="659" alt="shipcloudsettings" src="https://user-images.githubusercontent.com/5707341/28838735-8c44d530-76f1-11e7-94b6-f48f4a50ca02.png">

You probably "just" need to add the phone field here and then reference it as part of the sender address within the order, just like with all the other fields defined in here.

**Comment by andrecedik** [comment]
Ok, since it's merged it is fixed and I'm closing this issue
