### ISSUE TITLE
Making Plugin WordPress.org ready

### ISSUE THREAD

**Issue by mahype** [awsmug/shipcloud-for-woocommerce#94]
- [x] Adding english text
- [ ] Adding german text
- [x] Adding header image

**Comment by andrecedik** [comment]
Here are the German and English texts:
[shipcloud-for-WooCommerce-plugin-description.pdf](https://github.com/awsmug/shipcloud-for-woocommerce/files/1054577/shipcloud-for-WooCommerce-plugin-description.pdf)

**Comment by andrecedik** [comment]
@mahype do we know if we can upload a header image for each specific language? I currently only have a German version at hand.

**Comment by mahype** [comment]
It is only possible to put one image for all languages into the repository :(

**Comment by andrecedik** [comment]
Too bad. Ok, I'll get us a new one since it won't make sense to have German text be included in there.

**Comment by andrecedik** [comment]
Hmm, I have no idea, why we're using a sub headline now, but here we go.
![shipcloud-for-woocommerce-plugin-heaader](https://user-images.githubusercontent.com/5707341/26890803-2a7e6726-4bb3-11e7-8f0a-23024ece1c48.jpg)

**Comment by andrecedik** [comment]
Duh, I've made a few screenshots, but they are in German. Should we use English screens?!?

<img width="781" alt="woocommerce_einstellungen_versand" src="https://user-images.githubusercontent.com/5707341/26890979-b49b8ba0-4bb3-11e7-8af0-f16bbf97ef99.png">
<img width="691" alt="woocommerce_einstellungen_versandauswahl" src="https://user-images.githubusercontent.com/5707341/26890980-b4abdcee-4bb3-11e7-992e-e729de57ab16.png">
<img width="936" alt="woocommerce_paket_dimensionen_ausgefuellt" src="https://user-images.githubusercontent.com/5707341/26890981-b4b17e10-4bb3-11e7-9829-be3b3fb3ba75.png">
<img width="935" alt="woocommerce_paket_dimensionen" src="https://user-images.githubusercontent.com/5707341/26890982-b4b32a3a-4bb3-11e7-8dbc-6ba72b7cea0e.png">
<img width="952" alt="woocommerce_paketvorlagen_bearbeiten" src="https://user-images.githubusercontent.com/5707341/26890983-b4b7f51a-4bb3-11e7-9b12-3b48ae2e78e1.png">
<img width="1254" alt="woocommerce_paketvorlagen_uebersicht" src="https://user-images.githubusercontent.com/5707341/26890984-b4bb677c-4bb3-11e7-8a3b-dc79f1617d1d.png">
<img width="1251" alt="woocommerce_stapelverarbeitung" src="https://user-images.githubusercontent.com/5707341/26890985-b4c08fcc-4bb3-11e7-9eef-300d409c7716.png">
<img width="936" alt="woocommerce_versand_addressen" src="https://user-images.githubusercontent.com/5707341/26890986-b4c921a0-4bb3-11e7-9105-234e514ca498.png">

**Comment by andrecedik** [comment]
Ok, let's use this one for the start.
![shipcloud-for-woocommerce-plugin-header](https://user-images.githubusercontent.com/5707341/26891410-3329436c-4bb5-11e7-87d3-d1f742daaf4f.jpg)

**Comment by mahype** [comment]
@andrecedik Yes we should use english screens, but we don't have to. I will take yours at the moment.

**Comment by mahype** [comment]
Gibt es auch Beschreibungen zu dem Bildern in deutsch und englisch? @andrecedik

**Comment by andrecedik** [comment]
Ok, I've added a few small descriptions to each screenshot above @mahype

**Comment by mahype** [comment]
Thank you! :) I have added it now to the sources. At the first moment the plugin will be only available in english. At the moment I will be the project translation editor (this is the role which you need to add the translations to the directory), I will add the german language.
