### ISSUE TITLE
Problems after merging and API changes

### ISSUE THREAD

**Issue by sourcerer-mike** [awsmug/shipcloud-for-woocommerce#96]
The merge brought in code that should not be there.

- API returns errors about invalid mail address (which it didn't until now).
- components/woo/order-bulk.php:99: Complete foreach revived
- components/woo/order-bulk.php:328: Getter method used which is not defined.

I can't really tell if this thing is working on all edges. Plenty things were fixed but please quadruple check all cases that come to your mind @andrecedik @mahype . Please add problems as comments here, I flag them as soon as they are resolve. Don't bother if they are already reported or not just flush all information here - I take care of it. Remember that everything we write here is public.

Use this code please: https://github.com/awsmug/shipcloud-for-woocommerce/tree/release/1.3.0

Furthermore I feel the urge to wrap a test around some places now. Consider this to be a exception which will take less effort from you the more we let some script check all those assertions.

**Comment by andrecedik** [comment]
Hi @sourcerer-mike can you give me the error that you're getting about the ***invalid address***? I'll check what could be the problem there. Thanks

**Comment by sourcerer-mike** [comment]
@andrecedik the invalid mail address is a valid message but wasn't thrown by the API before.
The mail address for one order was "root@127.0.0.1" (me on my dev machine).
I guess some maintainer or developer got mails about created labels and added the message recently.

IMHO this message can stay there. Are there some other validations added besides this one?

**Comment by andrecedik** [comment]
Oh, I see what the problem is. The error message is coming from DHL. You we're supplying the additional service *advance_notice* and there you defined the email address that should be notified about the shipment to be (as you mentioned above) "root@127.0.0.1". Apparently DHL is now checking the email address that you supplied. So it's probably nothing you can fix at your end.

**Comment by mahype** [comment]
> components/woo/order-bulk.php:99: Complete foreach revived

I just see "@param array $actions Bulk actions" in this line. I think the lines have moved ;)

>components/woo/order-bulk.php:328: Getter method used which is not defined.

Which function is not defined? I just see the function "wcsc_get_carrier_display_name", which is defined in woocommerce-shipcloud-functions.php. I think thats also the problem of the moved lines.

**Comment by mahype** [comment]
Please pull the code before checking this errors. I have changed a little bit.
