### ISSUE TITLE
Create shipment form not fully shown

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#97]
It seems that there is a problem with the create shipment form in version 1.2.1. We've got 2 customers who send us the following screenshots:

Case 1
![shipment_form_internet_explorer](https://user-images.githubusercontent.com/5707341/27217257-6a4967a8-5279-11e7-8343-36e769bf3ac5.png)

Case 2
![image](https://user-images.githubusercontent.com/5707341/27217256-6a494aa2-5279-11e7-825e-ddc5144b8499.png)

As you can see one was made using the internet explorer (case 1), the other seems to be a Mac system (case 2). It's pretty weird that you can't even see the shipment description input. I'd say there's some kind of problem with the floats in css, but that wouldn't explain the missing input field.

**Comment by mahype** [comment]
Do you have tried to deactivate other plugins?

**Comment by sourcerer-mike** [comment]
@mahype I remember that an "->id" became "->get_id()".
Question is: Why was that? Did that resolve some issue?

Because the solution for this issue is to rollback and use the `->id` property access again (see last commit, above).

**Comment by mahype** [comment]
WooCommerce changed the property $id in orders to private, so that you should use the function get_id() of the order object.  Crazy that this makes problems.

**Comment by sourcerer-mike** [comment]
Ah. Damn I see this message now. Well then, we need to divide between Woo 2 and Woo 3 I guess.

**Comment by sourcerer-mike** [comment]
So I made some strategy around it using "get_id" if present, otherwise "->id" @mahype .
Sorry for reading this that late.
