### ISSUE TITLE
Postcode not taken from Settings

### ISSUE THREAD

**Issue by mahype** [awsmug/shipcloud-for-woocommerce#98]
If I want to create a label, the plugin warns me that the postcode is not available. If I take a look in the settings, I can see a plugin. I think this is because if the merging problems because we already worked on this point.

**Comment by sourcerer-mike** [comment]
@mahype - looks good. Please double check.

I entered an address in the shipcloud settings,
went into an order,
checked that the postcode/zip-code is filled out
and generated a label.
No error message appeared.
