### ISSUE TITLE
Invoiceaddress field "suite" not used for creating shipping label

### ISSUE THREAD

**Issue by andrecedik** [awsmug/shipcloud-for-woocommerce#99]
When entering an invoice address customers have the option of supplying a field called `billing_address_2` which has the placeholder *Appartment, Suite, Einheit etc. (optional)*. 

![woocommerce_invoice_address](https://user-images.githubusercontent.com/5707341/27371543-8eac2a9a-5661-11e7-9605-dca8683f4a26.png)

If a values was entered by a customer I'd expect this value to be used as the `care_of` (c/o) value for the shipping address, but it's not used at all it seems.

![woocommerce_ship_to_address](https://user-images.githubusercontent.com/5707341/27371561-9f58876c-5661-11e7-8d9d-b3bb0ed6f78c.png)

**Comment by sourcerer-mike** [comment]
Tested successfully (see screen shot). What about the recipient_address_2 ?

![image](https://user-images.githubusercontent.com/2559177/27390286-3314fc26-56a1-11e7-90f3-f6c69e270aaa.png)

**Comment by andrecedik** [comment]
Sounds good. I'd say that this should also be available for the `recipient_address_2`.

**Comment by sourcerer-mike** [comment]
@andrecedik "Billing address 2" will be default for "care of"
but "Shipping address 2" can override that.

Done @mahype . I guess the whole 1.3.1 is done.

**Comment by mahype** [comment]
That sounds good! I will take a look at it!
